services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    volumes:
      - ./backend/src:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env.sample
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
        - action: restart
          path: ./backend/src
  static_html:
    build:
      context: ./static_files
      dockerfile: Dockerfile
    command: python -m http.server 8000
    ports:
      - 3000:8000
    volumes:
      - ./static_files/src:/app
