services:
  static_html:
    build:
      context: ./static_files
      dockerfile: Dockerfile
    command: python -m http.server 8000
    ports:
      - 3000:8000
    volumes:
      - ./static_files/src:/app
